<?php

namespace ContainerV8QbUvf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthCheckGetControllerService extends Qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer
{
    /**
     * Gets the public 'Qm\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController' shared autowired service.
     *
     * @return \Qm\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthCheck/HealthCheckGetController.php';

        return $container->services['Qm\\Apps\\Backoffice\\Backend\\Controller\\HealthCheck\\HealthCheckGetController'] = new \Qm\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController();
    }
}
