<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0xqQ5S\qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0xqQ5S/qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX0xqQ5S.legacy');

    return;
}

if (!\class_exists(qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX0xqQ5S\qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer::class, false);
}

return new \ContainerX0xqQ5S\qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer([
    'container.build_hash' => 'X0xqQ5S',
    'container.build_id' => '9fd5427a',
    'container.build_time' => 1684163138,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0xqQ5S');
