<?php

namespace ContainerX0xqQ5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthCheckGetControllerService extends qm_Apps_Backoffice_Backend_BackofficeBackendKernelDevDebugContainer
{
    /**
     * Gets the public 'qm\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController' shared autowired service.
     *
     * @return \qm\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthCheck/HealthCheckGetController.php';

        return $container->services['qm\\Apps\\Backoffice\\Backend\\Controller\\HealthCheck\\HealthCheckGetController'] = new \qm\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController();
    }
}
